spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

app:
  artifactId: @project.artifactId@

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: qwer1234!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/myrecipes

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.batch: DEBUG

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: local.static.myrecipes.link

app:
  popular-recipes:
    page-size: 9

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.10.206/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: qwer1234!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  data:
    mongodb:
      uri: mongodb://10.0.10.206:27017/myrecipes
      username: mruser
      password: qwer1234!

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: dev.static.myrecipes.link

app:
  popular-recipes:
    page-size: 9

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.10.206/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: qwer1234!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  data:
    mongodb:
      uri: mongodb://10.0.10.206:27017/myrecipes
      username: mruser
      password: qwer1234!

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: static.myrecipes.link

app:
  popular-recipes:
    page-size: 9
